### PR TITLE
Add my test for grains

### PR DESCRIPTION
**Pull request by kayodeadeniyi**
This is my solutions for grains

### CODE REVIEW

**Comment by kayodeadeniyi** [comment]
@GiovanniSM20 I'm doing them separately and I don't want to have to wait till I'm done with everything before creating a PR.

**Comment by kayodeadeniyi** [comment]
@GiovanniSM20 I will pull master so as to use the ruby folder though

**Comment by GiovanniSM20** [comment]
I'm waiting for your "principal" pull request

**Comment by kayodeadeniyi** [comment]
@GiovanniSM20 Done

**Comment by GiovanniSM20** [comment]
Nice! @kayodeadeniyi 

Keep contribute :+1:

**Pull request merged**
